### ISSUE TITLE
Analyze Zimbra's default db struture and storage data

### ISSUE THREAD

**Issue by fciubotaru** [fciubotaru/z-pec#4]
Points of interest:
- overview of db scheme
- relation to PEC specifications regarding storage(see: http://tools.ietf.org/html/rfc6109)
- message ids, account info, etc
- db references to filesystem(eg: attachments, email message bodies, other)
- storage of rejected or infected messages
- other storage elements

**Comment by csfercoci** [comment]
Zimbra arhitecture:
http://www.zimbra.com/docs/ne/8.0.2/administration_guide/wwhelp/wwhimpl/js/html/wwhelp.htm#href=ZCS_8_0_2_Admin_Guide.System_Architecture.html

Zimbra packages:
http://www.zimbra.com/docs/ne/8.0.2/administration_guide/wwhelp/wwhimpl/js/html/wwhelp.htm#href=ZCS_8_0_2_Admin_Guide.Zimbra_Application_Packages.html

File  tree structure of the  project:
http://www.zimbra.com/docs/ne/8.0.2/administration_guide/wwhelp/wwhimpl/js/html/wwhelp.htm#href=ZCS_8_0_2_Admin_Guide.Zimbra_System_Directory_Tree.html

Important role in this application has zimbra mailboxserver.
http://www.zimbra.com/docs/ne/8.0.2/administration_guide/wwhelp/wwhimpl/js/html/wwhelp.htm#href=ZCS_8_0_2_Admin_Guide.Mailbox_Server.html

Data are stored in 3 main parts : 
immutable message itself, that is stored on filesistem as a standard RFC message 
metadata for that message that is stored in the database 
indexed message with  lucene engine 
This is explained in details on the link provided above.

EVERY NEW USER ACCOUNT CREATE HIS OWN DATABASE with name MBOXGROUP+ ACCOUNT_ID

**Comment by csfercoci** [comment]
Images below are structure of the database for zimbra server

Zimbra database is unique and contains all metadata regarding email accounts
![zimbra-db](https://f.cloud.github.com/assets/3026315/49653/c16c4180-5973-11e2-84bd-339e787276af.png)

Every email account has his own database MboxGroup+accountID 
![mboxgroup_accountId](https://f.cloud.github.com/assets/3026315/49654/c19b6eec-5973-11e2-9e62-125eb182f438.png)
